### ISSUE TITLE
分类器xml文件

### ISSUE THREAD

**Issue by khl-i** [guanking/FaceDetect#1]
您好，我运行您的项目可以很顺利的检测到人脸，非常感谢您的代码！
分类器xml文件是您自己定义的吗？如何制作呐？能够分享一下。
                                                                                      ——90后学子

**Comment by guanking** [comment]
你说的xml文件，我使用的是OpenCV自带的文件，你可以参考下[OpenCV官网](https://opencv.org/)找找资料

**Comment by guanking** [comment]
你说的xml文件，我使用的是OpenCV自带的文件，你可以参考下[OpenCV官网](https://opencv.org/)找找资料
