### ISSUE TITLE
你好,关于ui_FaceDetactUI.h文件找不到怎么办呀

### ISSUE THREAD

**Issue by coldcoda** [guanking/FaceDetect#2]
您好, @guanking 
我在运行的时候提示找不到ui_FaceDetactUI.h文件,我应该怎么解决呀?

![image](https://user-images.githubusercontent.com/37976152/61134189-a2634880-a4f1-11e9-9907-c2498e7b2a95.png)
麻烦您啦,希望您看到的话可以回我一下,谢谢您

**Comment by guanking** [comment]
在`UI`目录文件夹下面有一个`FaceDetactUI.ui`文件，是使用qt做出来的界面文件。然后你缺少的这个文件是FaceDetactUI.ui生成的。生成过程你可以看下QT的使用

**Comment by coldcoda** [comment]
您好,
因为我第一次使用Qt,百度了一些教程,可能问题比较傻,但是我搜了好久,还是没能解决这个问题,所以,麻烦您啦!
关于ui_FaceDetactUI.h这个头文件,Qt Creator运行的时候不是一般都可以自动生成吗?为什么不可以自动生成呢?


然后我使用uic生成了ui_FaceDetactUI.h和ui_FaceDetactUI.cpp文件,添加到工程里之后,出现了好多链接错误,不知道为什么?


仔细看了一下.pro文件,也没有发现哪里存在问题,不知道怎么解决了.


真是不好意思,还是决定再写一封邮件问您,希望可以解决.


我是直接打开您的.pro工程文件的.使用的是Qt5,然后修改了QtGui为QtWidgets,以及注释了Qt3Support的相关头文件.








------------------ 原始邮件 ------------------
发件人: "Black"<notifications@github.com>;
发送时间: 2019年7月13日(星期六) 晚上11:39
收件人: "guanking/FaceDetect"<FaceDetect@noreply.github.com>;
抄送: "xuegougou"<1927303313@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [guanking/FaceDetect] 你好,关于ui_FaceDetactUI.h文件找不到怎么办呀 (#2)




在UI目录文件夹下面有一个FaceDetactUI.ui文件，是使用qt做出来的界面文件。然后你缺少的这个文件是FaceDetactUI.ui生成的。生成过程你可以看下QT的使用

**Comment by guanking** [comment]
我们的开发流程可能有点不一样啊：我是直接在linux下面开发的。从ui文件到h文件的转化是通过qmake命令来完成的，具体的过程我在readme文件中写了。
然后听你说，感觉你在两个地方遇到了问题：
+ UI文件转化为代码文件
这个问题不管你是linux还是windows，只要出来源文件了基本不会有什么问题
+ 链接错误
首先你要确认是链接头文件出问题了还是库出问题了。我的工程是直接使用include来指定的，你那边的话就要保证的qt和opencv对应的头文件都可以正常被找到；如果链接库出问题，你要确定是否就要看具体是哪个库，不过我在linux下没有遇到这个问题。
